### ISSUE TITLE
Possible node_modules removal bug?

### ISSUE THREAD

**Issue by ilyvion** [scottcorgan/reinstall#2]
```
P:\Development\cmsng>reinstall

Removing node_modules directory ...
'rm' is not recognized as an internal or external command,
operable program or batch file.
[...]
```

I don't think that works quite like it's supposed to... The command you want is `rmdir /s /q`.

**Comment by scottcorgan** [comment]
Because I made this quick, it was for Mac only. I'm open for a PR to make this work on all platforms!
